#!/usr/bin/expect
set timeout 30
set password "1q2ws3edcQ123"
set host "root@115.191.56.242"
set ssh_opts "-o StrictHostKeyChecking=no -o GSSAPIAuthentication=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30"

spawn ssh {*}$ssh_opts $host "docker ps --format 'table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Ports}}'"
expect {
    -re ".*assword:" {
        send "$password\r"
        exp_continue
    }
    eof
}
